In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os 
%matplotlib inline
import seaborn as sns

In [2]:
path='/home/heruhe/Desktop/Ga2o3/cascade/5type/1500ev'
os.chdir(path)
#list success cascades info according the obtained data last frame
success_s=[]
for i in range(180):
    if os.path.isfile('./data.lastframe{}'.format(i)):
        success_s.append(i)
success_s=np.array(success_s)

In [3]:
#seperate frames into 2 group according to the PKA atom type atom is Ga or O 
pkatype=np.zeros(len(success_s))
for i in range(len(success_s)):
    file="PKA_inf{}.txt".format(success_s[i])
    f=open(file)
    pkatype[i]=int(f.readlines()[0].split()[2])

#frame array which PKA atom is Ga
PKA_Ga_frame=success_s[np.where(pkatype<=2)[0]]
#frame array which PKA atom is O
PKA_O_frame=success_s[np.where(pkatype>2)[0]]

In [4]:
#reading all atoms final position
df=pd.read_csv('data.lastframe0', skiprows = 17, nrows=160000,sep=" ")

df=df.reset_index()
df.drop(columns=df.columns[-3:], axis=1, inplace=True)
df.columns=['Particle Identifier','Particle Type','x','y','z']
df

        Particle Identifier  Particle Type           x           y          z
0                         1              2    1.845126    1.255174   1.063093
1                        31              5    1.881316    2.732757   2.571495
2                     72002              2    4.015145   -0.182397  55.841545
3                        12              5    3.882601    1.277987   1.429007
4                        22              2    3.966905    2.830614   2.924220
...                     ...            ...         ...         ...        ...
159995                79545              2  104.993211  114.160621  58.824468
159996                87802              2   64.713302  117.287442  58.898732
159997                79887              1   91.947556  118.784871  58.802763
159998                79899              3   94.937577  117.322769  58.812957
159999                87929              4  103.033081  117.264780  58.879230

[160000 rows x 5 columns]

In [5]:

#read defects sites original position
odf=pd.read_csv('Idefects_original_position0.csv')
#read interstitial atoms final position
ddf=pd.read_csv('Idefects_displaced_position0.csv')
ddf.drop(columns=ddf.columns[0], axis=1, inplace=True) #delete unneccessary columns
#delete original atoms in the defects sites, obtain interstitial atoms position info
I_atomsdf=ddf.drop(pd.Index(np.where(ddf['Particle Identifier'].isin(odf['Particle Identifier']))[0]))
I_atomsdf.reset_index(drop=True, inplace=True)
I_atomsdf

,Particle Type,x,y,z,Particle Identifier,frame,pka_type,site_type,site_identify
0,2,57.583673,27.494610,69.238758,89785,0,4,3,89780
1,1,45.086401,22.800575,70.791912,97748,0,4,3,97360
2,3,52.079560,30.561329,69.907942,98174,0,4,3,89793
3,3,56.552865,24.552427,74.016040,97779,0,4,3,97400
4,3,45.571374,27.407635,82.750182,98139,0,4,3,105759
5,3,50.399860,28.980350,80.823561,114174,0,4,1,105783
6,3,56.678545,33.674167,61.895619,82200,0,4,1,82167
7,3,55.289041,33.034466,64.727260,82180,0,4,2,82185
8,2,54.696391,34.765730,65.402545,82565,0,4,4,90189
9,1,45.235362,39.936079,71.914450,98548,0,4,2,98545
10,1,60.666694,24.267835,73.439863,89788,0,4,1,97803
11,4,106.846485,35.251226,39.671269,50356,0,4,1,50348
12,1,112.286020,35.203183,49.807088,66764,0,4,1,66384
13,2,87.555910,42.927667,48.618026,75082,0,4,1,67083
14,3,105.596377,60.397134,51.059780,68339,0,4,3,67960
15,1,92.157619,45.816620,51.311193,67087,0,4,5,67097
16,5,117.200307,42.802201,53.395597,66792,0,4,1,66787
17,5,88.273542,47.920729,54.853016,75112,0,4,3,75113
18,3,70.024977,34.081509,59.257057,82220,0,4,3,74239
19,1,93.976243,52.367378,60.154763,83508,0,4,2,83505
20,3,100.244689,38.363513,63.513181,82759,0,4,3,82733
21,5,112.606762,36.820515,66.938714,90738,0,4,3,90774

In [21]:
i=89785
#obtain interstitial atom's positon
x=I_atomsdf[I_atomsdf['Particle Identifier']==i].at[0,'x']
y=I_atomsdf[I_atomsdf['Particle Identifier']==i].at[0,'y']
z=I_atomsdf[I_atomsdf['Particle Identifier']==i].at[0,'z']
#regard the interstitial atom as center, choose a cube distrcition, extract all atoms info in the cube  
cube_df = df[(np.abs(df.x-x)<3)& (np.abs(df.y-y)<3)&(np.abs(df.z-z)<3)]
print(df[df['Particle Identifier']==i])
#In the cube, calculate each atom's distance with the center interstitial atom
cube_df.loc[:,'distance']=np.sqrt((cube_df.x-x)**2+(cube_df.y-y)**2+(cube_df.z-z)**2)
cube_df.sort_values(by=['distance'],inplace=True)
cube_df

       Particle Identifier  Particle Type          x          y          z
11897                89800              3  56.422704  29.087495  69.080771
       Particle Identifier  Particle Type          x         y          z
11900                89785              2  57.583673  27.49461  69.238758

/tmp/ipykernel_3804/409715358.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cube_df.loc[:,'distance']=np.sqrt((cube_df.x-x)**2+(cube_df.y-y)**2+(cube_df.z-z)**2)
/tmp/ipykernel_3804/409715358.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cube_df.sort_values(by=['distance'],inplace=True)

,Particle Identifier,Particle Type,x,y,z,distance
11900,89785,2,57.583673,27.494610,69.238758,0.000000
12509,97798,5,58.601044,27.509772,70.795996,1.860179
11808,89780,3,56.460874,26.024481,68.987722,1.866809
11899,89799,3,58.469070,27.572307,67.502038,1.950938
11897,89800,3,56.422704,29.087495,69.080771,1.977395
12421,97766,2,58.189600,26.083425,72.009718,3.168093
12417,97777,5,56.334260,25.957671,71.738757,3.189547
11806,89767,1,55.407774,25.890153,67.434492,3.250261
11895,89787,1,55.226979,29.049171,67.578494,3.275232
12422,97778,5,58.295308,24.563159,70.534122,3.282955
11903,89795,4,60.436842,29.172728,68.998725,3.318775
12416,89765,2,56.409999,24.537273,70.263656,3.342719
12506,90165,2,56.299987,30.424211,70.482280,3.431728
11809,89766,2,58.665927,26.063369,66.304899,3.439077
11898,89786,2,58.421834,29.045862,66.285366,3.439683
12508,97786,2,58.656366,29.157685,72.101355,3.480078
12505,97797,5,56.618431,29.345076,72.062107,3.511013
11810,89768,1,59.480060,24.528809,68.956158,3.531589

In [31]:
I_atomsdf[I_atomsdf['Particle Identifier']==97748].values[0][1]

45.086401469306296

In [32]:
i=97748
#obtain interstitial atom's positon
x=I_atomsdf[I_atomsdf['Particle Identifier']==i].values[0][1]
y=I_atomsdf[I_atomsdf['Particle Identifier']==i].values[0][2]
z=I_atomsdf[I_atomsdf['Particle Identifier']==i].values[0][3]
print(df[df['Particle Identifier']==i])
#regard the interstitial atom as center, choose a cube distrcition, extract all atoms info in the cube  
cube_df = df[(np.abs(df.x-x)<3)& (np.abs(df.y-y)<3)&(np.abs(df.z-z)<3)]

#In the cube, calculate each atom's distance with the center interstitial atom
cube_df.loc[:,'distance']=np.sqrt((cube_df.x-x)**2+(cube_df.y-y)**2+(cube_df.z-z)**2)
cube_df.sort_values(by=['distance'],inplace=True)
cube_df

       Particle Identifier  Particle Type          x          y          z
12341                97748              1  45.086401  22.800575  70.791912

/tmp/ipykernel_3804/2848997429.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cube_df.loc[:,'distance']=np.sqrt((cube_df.x-x)**2+(cube_df.y-y)**2+(cube_df.z-z)**2)
/tmp/ipykernel_3804/2848997429.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cube_df.sort_values(by=['distance'],inplace=True)

,Particle Identifier,Particle Type,x,y,z,distance
12341,97748,1,45.086401,22.800575,70.791912,0.000000
12342,97360,3,44.144893,22.761021,72.363566,1.832511
11723,89357,5,44.281885,22.900648,69.080392,1.893823
12343,89359,3,46.184002,21.214508,70.645677,1.934353
12407,89739,3,46.452559,24.172838,70.310572,1.995290
11717,89347,1,42.506092,22.874787,69.734448,2.789576
11729,89346,2,46.850523,22.972018,68.559335,2.850600
12408,97728,1,47.262884,24.252115,72.052186,2.903848
12405,97740,3,44.637996,25.546740,71.863878,2.981878
12345,97348,1,47.435907,21.100262,72.050814,3.161657
12406,97725,2,44.227688,24.500368,73.381611,3.214533
12336,89356,4,42.199007,21.301111,70.544630,3.262911
12952,97345,2,44.223731,21.304955,73.677370,3.362580
12339,89327,1,43.394582,19.864551,70.645499,3.391744
12403,89736,4,42.174278,24.520735,70.534105,3.392032
13029,97738,5,46.333098,24.236419,73.694309,3.469843
12957,97358,5,46.246368,21.251754,73.707967,3.499677
11719,89337,5,44.373826,19.865467,68.971648,3.526469
11722,89358,5,46.352508,21.272158,67.866964,3.534743
11727,89326,2,46.368331,19.815572,69.268558,3.588063
12947,97349,4,42.160695,21.336467,73.544445,4.275490
13022,97729,4,42.287768,24.470795,73.726049,4.385332

In [ ]:
for i in I_atomsdf['Particle Identifier']:
    x=I_atomsdf[I_atomsdf['Particle Identifier']==i]['x']
    y=I_atomsdf[I_atomsdf['Particle Identifier']==i]['y']
    z=I_atomsdf[I_atomsdf['Particle Identifier']==i]['z']
    near_df = df[() & (df.b != -1)]